<Project>
  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Version>1.1.3</Version>
    <Authors>BoltZip</Authors>
    <Company>BoltZip</Company>
    <Product>BoltZip</Product>
    <Copyright>Copyright (c) 2026 The BoltZip Authors</Copyright>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>
</Project>
